import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, History as HistoryIcon, Trash2, AlertCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import AnalysisCard from "@/components/history/AnalysisCard";
import Disclaimer from "@/components/ui/Disclaimer";

export default function History() {
  const [deleteId, setDeleteId] = useState(null);
  const queryClient = useQueryClient();

  const { data: analyses, isLoading, error } = useQuery({
    queryKey: ["skin-analyses"],
    queryFn: () => base44.entities.SkinAnalysis.list("-created_date", 50),
    initialData: []
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => base44.entities.SkinAnalysis.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["skin-analyses"] });
      setDeleteId(null);
    }
  });

  const handleDownload = (analysis) => {
    const report = `
SKINAID ANALYSIS REPORT
Generated: ${new Date(analysis.analysis_date || analysis.created_date).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMPORTANT DISCLAIMER
This report is for educational purposes only and does not constitute medical advice, 
diagnosis, or treatment. Please consult a qualified healthcare professional for any 
skin concerns.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUBJECT TYPE: ${analysis.subject_type === "pet" ? "Pet/Animal" : "Human"}
SEVERITY ESTIMATE: ${analysis.severity?.toUpperCase() || "Not determined"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

POSSIBLE CONDITIONS
${analysis.conditions?.map((c, i) => `
${i + 1}. ${c.name}
   ${c.description}
   Confidence: ${c.confidence ? Math.round(c.confidence * 100) + "%" : "N/A"}
`).join("") || "No conditions identified"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VISUAL OBSERVATIONS
${analysis.observations?.map((o, i) => `• ${o}`).join("\n") || "No observations recorded"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDED NEXT STEPS
${analysis.recommendations?.map((r, i) => `${i + 1}. ${r}`).join("\n") || "No recommendations"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report was generated by SkinAid - AI-Assisted Skin Screening Platform
    `.trim();
    
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `skinaid-report-${new Date(analysis.analysis_date || analysis.created_date).toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-8 px-4">
      <div className="container mx-auto max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <Link 
            to={createPageUrl("Home")}
            className="inline-flex items-center text-slate-600 dark:text-slate-400 hover:text-[#1E5EFF] transition-colors mb-4"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
                Analysis History
              </h1>
              <p className="text-slate-600 dark:text-slate-400 mt-2">
                Your saved skin analyses
              </p>
            </div>
            <div className="hidden sm:flex items-center gap-2 text-sm text-slate-500">
              <HistoryIcon className="w-4 h-4" />
              {analyses?.length || 0} analyses
            </div>
          </div>
        </div>

        {/* Content */}
        {isLoading ? (
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div 
                key={i}
                className="bg-white dark:bg-slate-800 rounded-2xl h-48 animate-pulse"
              />
            ))}
          </div>
        ) : analyses?.length === 0 ? (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white dark:bg-slate-800 rounded-3xl p-12 text-center border border-slate-200 dark:border-slate-700"
          >
            <div className="w-20 h-20 bg-slate-100 dark:bg-slate-700 rounded-2xl flex items-center justify-center mx-auto mb-6">
              <HistoryIcon className="w-10 h-10 text-slate-300 dark:text-slate-500" />
            </div>
            <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">
              No saved analyses yet
            </h3>
            <p className="text-slate-500 dark:text-slate-400 mb-6 max-w-sm mx-auto">
              When you save an analysis from your skin check, it will appear here
            </p>
            <Link to={createPageUrl("SkinCheck")}>
              <Button className="bg-[#1E5EFF] hover:bg-[#1a52e0] text-white">
                Start Your First Check
              </Button>
            </Link>
          </motion.div>
        ) : (
          <div className="space-y-4">
            <AnimatePresence>
              {analyses?.map((analysis) => (
                <AnalysisCard
                  key={analysis.id}
                  analysis={analysis}
                  onDelete={setDeleteId}
                  onDownload={handleDownload}
                />
              ))}
            </AnimatePresence>
          </div>
        )}

        {/* Disclaimer */}
        <div className="mt-8">
          <Disclaimer />
        </div>

        {/* Delete Confirmation */}
        <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete Analysis</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete this analysis? This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={() => deleteMutation.mutate(deleteId)}
                className="bg-red-500 hover:bg-red-600"
              >
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  );
}